apiVersion: extensions/v1beta1
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
metadata:
  name: forging-deployment
  labels:
    autolab/cpa: forging
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: forging-web-service
  template:
    metadata:
      labels:
        app: forging-web-service
    spec:
      containers:
      - image: autolab/forging:1.0.1
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["/app/app/start.sh"]
        name: forging-web-service
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: password
          - name: MYSQL_HOST
            value: 10.96.75.205
        # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
        livenessProbe:
         tcpSocket:
           port: 8055
        ports:
        - containerPort: 8055
        volumeMounts:
        - mountPath: /app
          subPath: forging
          name: containerized-forging-app-volume
      volumes:
      - name: containerized-forging-app-volume
        persistentVolumeClaim:
          claimName: containerized-app-forging-volume-claim
---

apiVersion: v1
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
kind: PersistentVolumeClaim
metadata:
  name: containerized-app-forging-volume-claim
  labels:
    cpa/volume: containerized-app-forging-source-code
  annotations:
    # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
      matchLabels:
        cpa/volume: containerized-app-forging-source-code
---

apiVersion: v1
# https://kubernetes.io/docs/concepts/services-networking/service/
kind: Service
metadata:
  name: forging-web-service
  labels:
    "autolab/cpa": forging
spec:
  ports:
  - port: 8055
    targetPort: 8055
    nodePort: 30055
    protocol: TCP
  selector:
    app: forging-web-service
  type: NodePort
  clusterIP: 10.102.220.191
